Edit ingredient
ndrbn0/Flavion pull request #24
Opened 2024-07-04 10:06 UTC by Sarahabidar

edit funktion

2024-07-04 11:08 UTC, NikRoe requested changes
Hi there,

I left some notes on how to fix the updated issue and also on some general improvements regarding the code.

2024-07-04 11:08 UTC, NikRoe commented on _styles.js
> +  background-color: ${(props) => (props.secondary ? "#6c757d" : "#007bff")};
You should prefix the props with "$" when working with styled components. Otherwise, you might get a notification in the console:

```suggestion
  background-color: ${(props) => (props.$secondary ? "#6c757d" : "#007bff")};
```

2024-07-04 11:08 UTC, NikRoe commented on _styles.js
> +    background-color: ${(props) => (props.secondary ? "#5a6268" : "#0056b3")};
You should prefix the props with "$" when working with styled components. Otherwise, you might get a notification in the console:

```suggestion
    background-color: ${(props) => (props.$secondary ? "#5a6268" : "#0056b3")};
```

2024-07-04 11:08 UTC, NikRoe commented on pages/_app.js
> +    );
```suggestion
  const updateIngredient = (_id, updatedIngredient) => {
    const editedIngredient = { _id, ...updatedIngredient };
    const updatedIngredients = ingredients.map((ingredient) =>
      ingredient._id === editedIngredient._id ? editedIngredient : ingredient
    );
```

2024-07-04 11:08 UTC, NikRoe commented on pages/ingredient/[id]/edit.js
> +    setFormData(false);
this is odd, you change the data from an object to a boolean;

you should keep the same data type

```suggestion
    setFormData({name: "",
    imgUrl: "",
    flavor: ""});
```

2024-07-04 11:08 UTC, NikRoe commented on pages/ingredient/[id]/edit.js
> +  }, [ingredient]);
You don't need a useEffect here, this will work just as fine:

```suggestion
const [formData, setFormData] = useState({
    name: ingredient.name || "",
    imgUrl: ingredient.imgUrl || "",
    flavor: ingredient.flavor || "",
  });
```

2024-07-05 08:17 UTC, MarenOelixtown approved these changes
Hi there, it looks nice . When the comments are removed the code review should approved.👍

2024-07-05 08:17 UTC, MarenOelixtown commented on pages/ingredient/[id]/edit.js
> +import ingredientsData from "@/assets/ingredients.json"; // Assuming this is where you store your ingredients data
```suggestion
import ingredientsData from "@/assets/ingredients.json"; 
```
Please remove comment from line3.

2024-07-05 08:17 UTC, MarenOelixtown commented on components/IngredientDetails.js
> +  Overlay,
```suggestion
  Overlay,
```
The naming for 'Overlay' is for me not really clear, maybe there is a clearer naming what it's doing?

2024-07-05 08:17 UTC, MarenOelixtown commented on components/EditIngredient.js
> +} from "@/_styles.js"; // Ensure Select is imported correctly
```suggestion
} from "@/_styles.js";
```
Please remove comment.

2024-07-05 08:20 UTC, ndrbn0 commented
> Hi there, it looks nice . When the comments are removed the code review should approved.👍

2024-07-05 08:23 UTC, merged